### ISSUE TITLE
Stack trace in nHibernate Query exception causes parser to hang

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/StackTraceParser#4]
Migrated from atifaziz/StackTraceFormatter#1, originally reported by @lukerogers:

> First off, this is not meant to be merged, just a way to show that an error in my application causes Hangfire to hang consuming 100% of the CPU and rendering it useless. I dug as far as I could but I am not smart enough for this one :)
> 
> In the [attached test](https://github.com/lukerogers/StackTraceFormatter/commit/3d7c61f6d35592af180360d7c6c253dfcd54df15) I have a fairly large stack track that contains 2 nHibernate queries. When it attempts to execute the string.Concat portion of the following line it hangs indefinietly:
> 
> `return string.Concat(Format(text, formatter ?? DefaultStackTraceHtmlFragments));`
> 
> It appears that the format parsing is successful but when it tries to enumerate over the formats it explodes. I'm assuming this has something to do with the nHibernate syntax but again, I'm not that smart of a guy.
> 
> If you can point me to anything so I can fix it and create a proper pull-request I would be greatful. If it is something you can fix easily, that's cool too. If there is any way I can help please let me know.
> 
> Thanks,
> Luke

**Comment by atifaziz** [comment]
The exception stack trace that demonstrates the issue is:

```
NHibernate.Exceptions.GenericADOException: Failed to execute multi query[SQL: select codingques0_.Id as Id2_0_, choicename1_.TextID as TextID130_1_, choicename1_.LanguageID as LanguageID130_1_, codingques0_.VersionStamp as VersionS2_2_0_, codingques0_.CreatedBy as CreatedBy2_0_, codingques0_.CreatedDateTime as CreatedD4_2_0_, codingques0_.LastUpdateBy as LastUpda5_2_0_, codingques0_.LastUpdateDateTime as LastUpda6_2_0_, codingques0_.CodingQuestionID as CodingQu7_2_0_, codingques0_.TreeID as TreeID2_0_, codingques0_.CodingSpec as CodingSpec2_0_, codingques0_.ClassificationKeywordID as Classif10_2_0_, codingques0_.ChoiceTextLTID as ChoiceT11_2_0_, codingques0_.PositionIndex as Positio12_2_0_, codingques0_.CodingValue as CodingV13_2_0_, codingques0_.ChoiceNumber as ChoiceN14_2_0_, codingques0_.[TreeID].GetLevel() as formula1_0_, (select case when exists(select 1 from Survey.CodingQuestionChoice a where a.CodingQuestionID = codingques0_.CodingQuestionID and a.TreeID.GetAncestor(1) = codingques0_.TreeID) then 1 else 0 end) as formula2_0_, choicename1_.LocalizedText as Localize3_130_1_, choicename1_.TextID as TextID0__, choicename1_.LanguageID as LanguageID0__ from Survey.CodingQuestionChoice codingques0_ left outer join Administration.LocalizedTextSequenced choicename1_ on codingques0_.ChoiceTextLTID=choicename1_.TextID where codingques0_.CodingQuestionID=?;
select codingques0_.Id as Id2_0_, codingques1_.ID as ID3_1_, codingques0_.VersionStamp as VersionS2_2_0_, codingques0_.CreatedBy as CreatedBy2_0_, codingques0_.CreatedDateTime as CreatedD4_2_0_, codingques0_.LastUpdateBy as LastUpda5_2_0_, codingques0_.LastUpdateDateTime as LastUpda6_2_0_, codingques0_.CodingQuestionID as CodingQu7_2_0_, codingques0_.TreeID as TreeID2_0_, codingques0_.CodingSpec as CodingSpec2_0_, codingques0_.ClassificationKeywordID as Classif10_2_0_, codingques0_.ChoiceTextLTID as ChoiceT11_2_0_, codingques0_.PositionIndex as Positio12_2_0_, codingques0_.CodingValue as CodingV13_2_0_, codingques0_.ChoiceNumber as ChoiceN14_2_0_, codingques0_.[TreeID].GetLevel() as formula1_0_, (select case when exists(select 1 from Survey.CodingQuestionChoice a where a.CodingQuestionID = codingques0_.CodingQuestionID and a.TreeID.GetAncestor(1) = codingques0_.TreeID) then 1 else 0 end) as formula2_0_, codingques1_.VersionStamp as VersionS2_3_1_, codingques1_.CodingQuestionChoiceID as CodingQu3_3_1_, codingques1_.StringPath as StringPath3_1_, codingques1_.StartCodingValue as StartCod5_3_1_, codingques1_.EndCodingValue as EndCodin6_3_1_, codingques1_.CodingSpec as CodingSpec3_1_, codingques1_.CreatedBy as CreatedBy3_1_, codingques1_.CreatedDateTime as CreatedD9_3_1_, codingques1_.LastUpdateBy as LastUpd10_3_1_, codingques1_.LastUpdateDateTime as LastUpd11_3_1_, codingques1_.CodingQuestionChoiceID as CodingQu3_0__, codingques1_.ID as ID0__ from Survey.CodingQuestionChoice codingques0_ left outer join Survey.CodingQuestionChoiceCodingRange codingques1_ on codingques0_.Id=codingques1_.CodingQuestionChoiceID where codingques0_.CodingQuestionID=?;
] ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Data.SqlClient.SqlConnection.ResolveTypeAssembly(AssemblyName asmRef, Boolean throwOnError)
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at System.Data.SqlClient.SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow)
   at System.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)
   at System.Data.SqlClient.SqlDataReader.GetValue(Int32 i)
   at NHibernate.Type.AbstractStringType.Get(IDataReader rs, Int32 index)
   at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Hydrate(IDataReader rs, Object id, Object obj, ILoadable rootLoadable, String[][] suffixedPropertyColumns, Boolean allProperties, ISessionImplementor session)
   at NHibernate.Loader.Loader.LoadFromResultSet(IDataReader rs, Int32 i, Object obj, String instanceClass, EntityKey key, String rowIdAlias, LockMode lockMode, ILoadable rootPersister, ISessionImplementor session)
   at NHibernate.Loader.Loader.InstanceNotYetLoaded(IDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, String rowIdAlias, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session)
   at NHibernate.Loader.Loader.GetRow(IDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session)
   at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.MultiQueryImpl.DoList()
```

**Comment by atifaziz** [comment]
Attaching a C# test script ([`StackTraceParser.zip`](https://github.com/atifaziz/StackTraceParser/files/173550/StackTraceParser.zip)) that can also be used to test and demonstrate the issue. The script contains an embedded version of [`StackTraceParser.cs` from release 1.1.1](https://github.com/atifaziz/StackTraceParser/blob/v1.1.1/StackTraceParser.cs) minus the namespace (since they're not allowed in scripts). I also added a timeout of 5 seconds to the `Regex` initialization in line 65. The script parses text over standard input and the emits the parsed stack trace frames and tokens.

Assuming the [exception text above](https://github.com/atifaziz/StackTraceParser/issues/4#issuecomment-196707664) is saved in a file called `test.txt`, then running the script as follows:

```
csi StackTraceParser.csx < test.txt
```

now effectively gives a timeout exception after 5 seconds:

```
System.Text.RegularExpressions.RegexMatchTimeoutException: The RegEx engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.
```

Looks like this is a case of a [_runaway regular expression_](http://www.regular-expressions.info/catastrophic.html) and the pattern needs to be rendered more specific.

I have also narrowed it down to the second line (starting with `select …`) causing the runaway. For example, just doing the following causes a timeout:

```
findstr "^select" test.txt | csi StackTraceParser.csx
```

Testing all other lines with `/v` giving the inverted matches of the culprit line:

```
findstr /v "^select" test.txt | csi StackTraceParser.csx
```

causes no problem and emits the following parsed output:

```
------------------------------------------------------------------------------
System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

Type          = System.Reflection.RuntimeAssembly
Method        = _nLoad
ParameterList = (AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

Type          = System.Reflection.RuntimeAssembly
Method        = InternalLoadAssemblyName
ParameterList = (AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Reflection.Assembly.Load(AssemblyName assemblyRef)

Type          = System.Reflection.Assembly
Method        = Load
ParameterList = (AssemblyName assemblyRef)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Data.SqlClient.SqlConnection.ResolveTypeAssembly(AssemblyName asmRef, Boolean throwOnError)

Type          = System.Data.SqlClient.SqlConnection
Method        = ResolveTypeAssembly
ParameterList = (AssemblyName asmRef, Boolean throwOnError)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)

Type          = System.TypeNameParser
Method        = ResolveAssembly
ParameterList = (String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)

Type          = System.TypeNameParser
Method        = ConstructType
ParameterList = (Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)

Type          = System.TypeNameParser
Method        = GetType
ParameterList = (String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)

Type          = System.Type
Method        = GetType
ParameterList = (String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Data.SqlClient.SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow)

Type          = System.Data.SqlClient.SqlConnection
Method        = CheckGetExtendedUDTInfo
ParameterList = (SqlMetaDataPriv metaData, Boolean fThrow)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)

Type          = System.Data.SqlClient.SqlDataReader
Method        = GetValueFromSqlBufferInternal
ParameterList = (SqlBuffer data, _SqlMetaData metaData)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
System.Data.SqlClient.SqlDataReader.GetValue(Int32 i)

Type          = System.Data.SqlClient.SqlDataReader
Method        = GetValue
ParameterList = (Int32 i)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Type.AbstractStringType.Get(IDataReader rs, Int32 index)

Type          = NHibernate.Type.AbstractStringType
Method        = Get
ParameterList = (IDataReader rs, Int32 index)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name)

Type          = NHibernate.Type.NullableType
Method        = NullSafeGet
ParameterList = (IDataReader rs, String name)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Persister.Entity.AbstractEntityPersister.Hydrate(IDataReader rs, Object id, Object obj, ILoadable rootLoadable, String[][] suffixedPropertyColumns, Boolean allProperties, ISessionImplementor session)

Type          = NHibernate.Persister.Entity.AbstractEntityPersister
Method        = Hydrate
ParameterList = (IDataReader rs, Object id, Object obj, ILoadable rootLoadable, String[][] suffixedPropertyColumns, Boolean allProperties, ISessionImplementor session)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Loader.Loader.LoadFromResultSet(IDataReader rs, Int32 i, Object obj, String instanceClass, EntityKey key, String rowIdAlias, LockMode lockMode, ILoadable rootPersister, ISessionImplementor session)

Type          = NHibernate.Loader.Loader
Method        = LoadFromResultSet
ParameterList = (IDataReader rs, Int32 i, Object obj, String instanceClass, EntityKey key, String rowIdAlias, LockMode lockMode, ILoadable rootPersister, ISessionImplementor session)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Loader.Loader.InstanceNotYetLoaded(IDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, String rowIdAlias, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session)

Type          = NHibernate.Loader.Loader
Method        = InstanceNotYetLoaded
ParameterList = (IDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, String rowIdAlias, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Loader.Loader.GetRow(IDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session)

Type          = NHibernate.Loader.Loader
Method        = GetRow
ParameterList = (IDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer)

Type          = NHibernate.Loader.Loader
Method        = GetRowFromResultSet
ParameterList = (IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer)
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 

------------------------------------------------------------------------------
NHibernate.Impl.MultiQueryImpl.DoList()

Type          = NHibernate.Impl.MultiQueryImpl
Method        = DoList
ParameterList = ()
Parameters    = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Collections.Generic.KeyValuePair`2[System.String,System.String]]
File          = 
Line          = 
```

**Comment by atifaziz** [comment]
§ II.5.3 Identifiers of [Standard ECMA-335 Common Language Infrastructure (CLI), 6th edition (June 2012)](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf) on page 110 has the following to say about validity of identifiers used for naming types, methods and parameters:

> ### II.5.3 Identifiers
> 
> Identifiers are used to name entities. Simple identifiers are equivalent to an ID. However, the ILAsm syntax allows the use of any identifier that can be formed using the Unicode character set (see Partition I). To achieve this, an identifier shall be placed within single quotation marks. This is
> summarized in the following grammar. 
> 
> `Id ::= ID | SQSTRING`
> 
> Several _Ids_ can be combined to form a larger _Id_, by separating adjacent pairs with a dot (.). An _Id_ formed in this way is called a _DottedName_. 
> 
> `DottedName ::= Id [‘.’ Id]*`
> 
> [Rationale: _DottedName_ is provided for convenience, since “.” can be included in an _Id_ using the _SQSTRING_ syntax. _DottedName_ is used in the grammar where “.” is considered a common character (e.g., in fully qualified type names) end rationale]
> 
> [Example: The following are simple identifiers:
> 
> ```
> A    Test    $Test    @Foo?    ?_X_    MyType`1`
> ```
> 
> The following are identifiers in single quotes:
> 
> ```
> 'Weird Identifier'
> 'Odd\102Char'
> 'Embedded\nReturn'
> ```
> 
> The following are dotted names:
> 
> ```
> System.Console
> 'My Project'.'My Component'.'My Name'
> System.IComparable`1 
> ```
> 
> end example] 
> 
> © Ecma International 2012

Earlier on the same page, ID is defined as:

> _ID_ is a contiguous string of characters which starts with either an alphabetic character (A–Z, a–z) or one of “_”, “$”, “@”, “`” (grave accent), or “?”, and is followed by any number of alphanumeric characters (A–Z, a–z, 0–9) or the characters “_”, “$”, “@”, “`” (grave accent), and “?”.

However, it looks like that a formatted stack trace (e.g. one emitted by [`Exception.ToString`](https://msdn.microsoft.com/en-us/library/system.exception.tostring%28v=vs.110%29.aspx) or [`Environment.StackTrace`](https://msdn.microsoft.com/en-us/library/system.environment.stacktrace%28v=vs.110%29.aspx)) does not follow these rules. For example, `<>c__DisplayClass36` and `<ExecuteClrQuery>b__35` in the stack trace fragment below should be quoted according to `SQSTRING` syntax but it isn't:

```
at LINQPad.ExecutionModel.Server.<>c__DisplayClass36.<ExecuteClrQuery>b__35()
```

This is the reason the Regex pattern used by the parser has been very generous & cannot be encoded to the specific rules laid out in the CLI specification.

**Comment by atifaziz** [comment]
Fixed by 7e1f01280b297f99e2cd3e47e54b7ff1fb140e70.

**Comment by lukerogers** [comment]
I definitely wouldn't have found that! Thanks for the help!

**Comment by atifaziz** [comment]
@lukerogers Would be a good idea to give a heads up to @odinserj to upgrade to the fixed version.

**Comment by odinserj** [comment]
Thanks guys for highlighting the issue, I'm pleased to see such a collaboration :heart:
