### ISSUE TITLE
Skips stack trace lines on .NET Core Linux

### ISSUE THREAD

**Issue by Gonyoda** [atifaziz/StackTraceParser#6]
Using StackTraceParser in .NET core on Linux it skips over lines in the stack trace that contain file and line information formatted using Linux paths instead of Windows.

Given:
>    at Elmah.ErrorLogPageFactory.FindHandler(String name) in /ELMAH/src/Elmah/ErrorLogPageFactory.cs:line 126
    at Elmah.ErrorLogPageFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated) in /ELMAH/src/Elmah/ErrorLogPageFactory.cs:line 66
    at System.Web.HttpApplication.MapHttpHandler(HttpContext context, String requestType, VirtualPath path, String pathTranslated, Boolean useAppConfig)
    at System.Web.HttpApplication.MapHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)";

Parse method skips over the lines containing filenames due to the forward slash formatted filenames.

**Comment by atifaziz** [comment]
Closed by 350c133775c070181636b4e315412c3311ece26d.

**Comment by atifaziz** [comment]
This is now fixed in the [1.3.0](https://github.com/atifaziz/StackTraceParser/releases/tag/v1.3.0) release. Thanks for reporting and the PR with the fix!
